In [1]:
import os
from os.path import join
from glob import glob
from math import sqrt
import numpy as np
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_palette('muted')
sns.set_style("whitegrid")

#subs = ['WMAZE_001']

subs = ['WMAZE_001', 'WMAZE_002', 'WMAZE_004', 'WMAZE_005', 'WMAZE_006',
        'WMAZE_007', 'WMAZE_008', 'WMAZE_009', 'WMAZE_010', 'WMAZE_012',
        'WMAZE_017', 'WMAZE_018', 'WMAZE_019', 'WMAZE_020', 'WMAZE_021',
        'WMAZE_022', 'WMAZE_023', 'WMAZE_024', 'WMAZE_026', 'WMAZE_027']

stim_sets = ['set1', 'set2', 'set3']

count_table = {}
ctstd_table = {}
rt_table = {}
rtstd_table = {}

for sub in subs:
    ct_dict = {}
    rt_dict = {}
    sub_dir = '/home/data/madlab/data/mri/wmaze/scanner_behav/{0}/'.format(sub)
    dir_file = glob(join(sub_dir, '{0}_wmazebl_2015*.txt'.format(sub)))    
    dir_file.sort() 

    for i, curr_set in enumerate(stim_sets):
        run1 = pd.read_table(dir_file[i * 2])
        run2 = pd.read_table(dir_file[i * 2 + 1])
        
        trialtype = np.empty(320,dtype=object)
        trialtype[:160] = run1['TrialType'].values
        trialtype[160:] = run2['TrialType'].values
        
        trial_shift1 = trialtype[1:] 
        trial_shift1 = np.append(trial_shift1, -1)
        trial_shift2 = trial_shift1[1:] 
        trial_shift2 = np.append(trial_shift2, -1)
        trial_shift3 = trial_shift2[1:] 
        trial_shift3 = np.append(trial_shift3, -1)
        trial_shift4 = trial_shift3[1:] 
        trial_shift4 = np.append(trial_shift4, -1)
        trial_shift5 = trial_shift4[1:] 
        trial_shift5 = np.append(trial_shift5, -1)
           
       
        f_BL0_C = np.where(((trialtype=='A')|(trialtype=='C'))&(trial_shift1=='B'))[0]
        f_BL1_C = np.where(((trialtype=='A')|(trialtype=='C'))&(trial_shift1=='BL')&(trial_shift2=='B'))[0] 
        f_BL2_C = np.where(((trialtype=='A')|(trialtype =='C'))&(trial_shift1=='BL')
                           &(trial_shift2=='BL')&(trial_shift3=='B'))[0] 
        f_BL3_C = np.where(((trialtype=='A')|(trialtype=='C'))&(trial_shift1=='BL')&(trial_shift2=='BL')
                           &(trial_shift3=='BL')&(trial_shift4=='B'))[0] 
        f_BL4_C = np.where(((trialtype=='A')|(trialtype=='C'))&(trial_shift1=='BL')&(trial_shift2=='BL')
                           &(trial_shift3=='BL')&(trial_shift4=='BL')&(trial_shift5=='B'))[0] 
                 
        for curr_type in ['f_BL0_C', 'f_BL1_C', 'f_BL2_C', 'f_BL3_C', 'f_BL4_C']:
            curr_name = '{0}'.format(curr_type)
            if not curr_name in ct_dict:
                ct_dict[curr_name] = []
            ct_dict[curr_name].append(len(eval(curr_name)))                          
    
    for key in ct_dict:
        ct_dict[key] = np.sum(ct_dict[key])
        if not key in count_table:
            count_table[key] = []
        count_table[key].append(ct_dict[key])
                
BLs_df = pd.DataFrame(count_table, index = subs)

In [2]:
ct_avg = {}
ct_std = {}
for curr_key in count_table:
    ct_avg[curr_key] = np.average(count_table[curr_key])
    ct_std[curr_key] = np.std(count_table[curr_key])    
count_average = pd.DataFrame(ct_avg, index = (1,))
count_std = pd.DataFrame(ct_std, index = (1,))

In [3]:
count_average

   f_BL0_C  f_BL1_C  f_BL2_C  f_BL3_C  f_BL4_C
1    180.2     45.0    10.65     2.85      0.6

In [4]:
count_std

    f_BL0_C   f_BL1_C   f_BL2_C   f_BL3_C   f_BL4_C
1  4.749737  5.234501  3.595483  1.851351  0.663325

In [5]:
BLs_df

           f_BL0_C  f_BL1_C  f_BL2_C  f_BL3_C  f_BL4_C
WMAZE_001      174       46       20        0        0
WMAZE_002      186       45        7        0        1
WMAZE_004      177       49       10        3        1
WMAZE_005      188       34       13        3        2
WMAZE_006      181       47        7        3        0
WMAZE_007      173       52       12        3        0
WMAZE_008      179       49        9        2        0
WMAZE_009      177       41       17        3        1
WMAZE_010      170       54       12        2        1
WMAZE_012      176       45       13        4        2
WMAZE_017      178       50        9        3        0
WMAZE_018      180       49        7        2        1
WMAZE_019      179       43       15        1        1
WMAZE_020      184       38       12        5        1
WMAZE_021      184       47        7        2        0
WMAZE_022      188       34        8        9        0
WMAZE_023      181       46        8        3        1
WMAZE_024      183       43       10        2        0
WMAZE_026      184       41       11        3        0
WMAZE_027      182       47        6        4        0

# Create EV files for RSA

In [4]:
import os
from os.path import join
from glob import glob
from math import sqrt
import numpy as np
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_palette('muted')
sns.set_style("whitegrid")


subs = ['WMAZE_001', 'WMAZE_002', 'WMAZE_004', 'WMAZE_005', 'WMAZE_006',
        'WMAZE_007', 'WMAZE_008', 'WMAZE_009', 'WMAZE_010', 'WMAZE_012',
        'WMAZE_017', 'WMAZE_018', 'WMAZE_019', 'WMAZE_020', 'WMAZE_021',
        'WMAZE_022', 'WMAZE_023', 'WMAZE_024', 'WMAZE_026', 'WMAZE_027']
stim_sets = ['set1', 'set2', 'set3']
count_table = {}
ctstd_table = {}
rt_table = {}
rtstd_table = {}

for sub in subs:
    ct_dict = {}
    rt_dict = {}
    sub_dir = '/home/data/madlab/data/mri/wmaze/scanner_behav/{0}/'.format(sub)
    dir_file = glob(join(sub_dir, '{0}_wmazebl_2015*.txt'.format(sub)))    
    dir_file.sort() 

    for i, curr_set in enumerate(stim_sets):
        for curr_run in ['1','2']:
            if curr_run == '1':
                run = pd.read_table(dir_file[i*2]) #create dataframe for text files to extract EVS
                run = run[:-3] #removal of the last 3 trials to avoid scanner artifact
            else:
                run = pd.read_table(dir_file[i*2+1])
                run = run[:-3]
        
            trialtype = run['TrialType'].values #convert dataframes into numpy arrays
            correct = run['Correct'].values
            resp = run['Resp'].values
            onsets = run['StimOnset'].values
        
            fixed_before = trialtype[:-1]
            fixed_before = np.insert(fixed_before, 0, -1)
            trial_shift1 = trialtype[1:] 
            trial_shift1 = np.append(trial_shift1, -1)
            trial_shift2 = trial_shift1[1:] 
            trial_shift2 = np.append(trial_shift2, -1)
        
            correct_shift1 = correct[1:] 
            correct_shift1 = np.append(correct_shift1, -1)
            correct_shift2 = correct_shift1[1:] 
            correct_shift2 = np.append(correct_shift2, -1)           
       
            f_C_corr = np.where((trialtype!='BL')&(trial_shift1=='B')&(correct_shift1==1))[0] 
            f_C_incorr = np.where((trialtype!='BL')&(trial_shift1=='B')&(correct_shift1==0))[0]         
            f_BL1_C = np.where(((fixed_before == 'A') | (fixed_before == 'C')) 
                                  & (trialtype == 'BL') & (trial_shift1 == 'B'))[0]  
            temp = np.concatenate([f_C_corr, f_C_incorr, f_BL1_C])
            temp = set(temp)
            x = set(np.arange(0,157))
            all_remaining = x.difference(temp)

            f_C_corr_onsets = onsets[f_C_corr]
            f_C_incorr_onsets = onsets[f_C_incorr]
            f_BL1_C_onsets = onsets[f_BL1_C]
            all_remaining_onsets = onsets[list(all_remaining)]

    
            mtrx = np.vstack((onsets, np.ones(len(onsets))*2.5, np.ones(len(onsets)))).T

            f_C_corr_mtrx = np.vstack((f_C_corr_onsets, np.ones(len(f_C_corr_onsets))*2.5,
                                       np.ones(len(f_C_corr_onsets)))).T
 
            f_C_incorr_mtrx = np.vstack((f_C_incorr_onsets, np.ones(len(f_C_incorr_onsets))*2.5,
                                          np.ones(len(f_C_incorr_onsets)))).T
    
            f_BL1_C_mtrx = np.vstack((f_BL1_C_onsets, np.ones(len(f_BL1_C_onsets))*2.5,
                                      np.ones(len(f_BL1_C_onsets)))).T

            all_remaining_mtrx = np.vstack((all_remaining_onsets, np.ones(len(all_remaining_onsets))*2.5,
                                            np.ones(len(all_remaining_onsets)))).T


            if not os.path.exists(join(sub_dir, 'model_RSA/')): #if directory does not exist
                os.makedirs(join(sub_dir, 'model_RSA/')) #create it

            if curr_run == '1': #if the first run in a stimulus set
                np.savetxt(sub_dir+'model_RSA/'+'run{0}.txt'.format(i*2+1),mtrx,delimiter='\t',fmt='%.4f')                
                for trial in ['f_C_corr', 'f_C_incorr', 'f_BL1_C', 'all_remaining']: #for all trial types
                    exec('np.savetxt(sub_dir+"model_RSA/"+"run{0}_{1}.txt",{1}_mtrx,delimiter="\t",fmt="%.4f")'.format(i*2+1,trial))

            else: #if the second run in a stimulus set
                np.savetxt(sub_dir+'model_RSA/'+'run{0}.txt'.format(i*2+2),mtrx,delimiter='\t',fmt='%.4f')                
                for trial in ['f_C_corr', 'f_C_incorr', 'f_BL1_C', 'all_remaining']:
                    exec('np.savetxt(sub_dir+"model_RSA/"+"run{0}_{1}.txt",{1}_mtrx,delimiter="\t",fmt="%.4f")'.format(i*2+2,trial))